# Generated by Django 2.2.1 on 2019-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField(choices=[('1', 1), ('2', 2)])),
                ('name', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('grade', models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4)])),
            ],
        ),
    ]
