# Generated by Django 2.2.1 on 2019-05-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_class_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='class',
            name='startTime',
        ),
        migrations.AddField(
            model_name='class',
            name='end1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='end2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='end3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='end4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='end5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='week1',
            field=models.IntegerField(blank=True, choices=[('mon', 0), ('tue', 1), ('wed', 2), ('thu', 3), ('fri', 4), ('sat', 5), ('sun', 6)], null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='week2',
            field=models.IntegerField(blank=True, choices=[('mon', 0), ('tue', 1), ('wed', 2), ('thu', 3), ('fri', 4), ('sat', 5), ('sun', 6)], null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='week3',
            field=models.IntegerField(blank=True, choices=[('mon', 0), ('tue', 1), ('wed', 2), ('thu', 3), ('fri', 4), ('sat', 5), ('sun', 6)], null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='week4',
            field=models.IntegerField(blank=True, choices=[('mon', 0), ('tue', 1), ('wed', 2), ('thu', 3), ('fri', 4), ('sat', 5), ('sun', 6)], null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='week5',
            field=models.IntegerField(blank=True, choices=[('mon', 0), ('tue', 1), ('wed', 2), ('thu', 3), ('fri', 4), ('sat', 5), ('sun', 6)], null=True),
        ),
    ]
