# Generated by Django 2.2.1 on 2019-05-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190511_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='week1',
            field=models.CharField(blank=True, choices=[('월', 'mon'), ('화', 'tue'), ('수', 'wed'), ('목', 'thu'), ('금', 'fri'), ('토', 'sat'), ('일', 'sun')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='week2',
            field=models.CharField(blank=True, choices=[('월', 'mon'), ('화', 'tue'), ('수', 'wed'), ('목', 'thu'), ('금', 'fri'), ('토', 'sat'), ('일', 'sun')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='week3',
            field=models.CharField(blank=True, choices=[('월', 'mon'), ('화', 'tue'), ('수', 'wed'), ('목', 'thu'), ('금', 'fri'), ('토', 'sat'), ('일', 'sun')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='week4',
            field=models.CharField(blank=True, choices=[('월', 'mon'), ('화', 'tue'), ('수', 'wed'), ('목', 'thu'), ('금', 'fri'), ('토', 'sat'), ('일', 'sun')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='week5',
            field=models.CharField(blank=True, choices=[('월', 'mon'), ('화', 'tue'), ('수', 'wed'), ('목', 'thu'), ('금', 'fri'), ('토', 'sat'), ('일', 'sun')], max_length=20, null=True),
        ),
    ]
