# Generated by Django 2.2.1 on 2019-05-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190511_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('majorCode', models.CharField(max_length=50)),
                ('studentId', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
