# Generated by Django 2.2.1 on 2019-06-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_edit_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edit',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='edit',
            name='type',
            field=models.CharField(choices=[('ADD', 'ADD'), ('REMOVE', 'REMOVE'), ('CODE', 'CODE'), ('NAME', 'NAME'), ('GRADE', 'GRADE'), ('PROFESSOR', 'PROFESSOR'), ('PLACE', 'PLACE'), ('SIZE', 'SIZE'), ('TIMEADD', 'TIMEADD'), ('TIMEREMOVE', 'TIMEREMOVE')], max_length=20),
        ),
    ]
