# Generated by Django 2.2.1 on 2019-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190615_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
