# Generated by Django 2.2.1 on 2019-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190616_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edit',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='edit',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
