# Generated by Django 2.2.1 on 2019-06-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190616_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='star',
            field=models.ManyToManyField(default=[], to='api.User'),
        ),
    ]
