# Generated by Django 2.2.1 on 2019-06-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190617_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='star',
            field=models.ManyToManyField(blank=True, default=[], to='api.User'),
        ),
    ]
